### GET APPLICATIONS
GET {{BASE_REQUEST}}/api/applications
Content-Type: application/json

### POST APPLICATIONS
POST {{BASE_REQUEST}}/api/applications
Content-Type: application/json
Accept: application/json

{
    "title": "Empresa 1",
    "type": "CMT",
    "company_id": 1
}

### POST SEND APPLICATIONS
POST {{BASE_REQUEST}}/api/applications/2/send
Accept: application/json

### POST ACCEPT APPLICATIONS
POST {{BASE_REQUEST}}/api/applications/2/accept
Accept: application/json

### POST ACCEPT APPLICATIONS
POST {{BASE_REQUEST}}/api/applications/2/reject
Accept: application/json

### GET COMPANIES
GET {{BASE_REQUEST}}/api/companies
Content-Type:application/json
Accept: application/json

### POST COMPANIES
POST {{BASE_REQUEST}}/api/companies
Content-Type: application/json
Accept: application/json

{
  "name": "UNINASSAU",
  "cnpj": "111111111111111",
  "address_string": "Rua das flores av. Antoinho, n.50001",
  "description": "Universidade Ensino Educacional"
}
